// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP4Gpq-qgZB3QYK9nHeAnm_Wnx0plI-eg',
    appId: '1:521661363433:web:24544fa8d0b20863466c78',
    messagingSenderId: '521661363433',
    projectId: 'projeektekmo',
    authDomain: 'projeektekmo.firebaseapp.com',
    storageBucket: 'projeektekmo.appspot.com',
    measurementId: 'G-ZQT8RS4WSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJLDr-E9X3mFvvNYNvI63Hqt2vEtdNHs',
    appId: '1:521661363433:android:3816a70d32fd2509466c78',
    messagingSenderId: '521661363433',
    projectId: 'projeektekmo',
    storageBucket: 'projeektekmo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-k7vIzarMmtWO42ztB1EZqSsfIgf97Ic',
    appId: '1:521661363433:ios:8393b3bd8ac5ce17466c78',
    messagingSenderId: '521661363433',
    projectId: 'projeektekmo',
    storageBucket: 'projeektekmo.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-k7vIzarMmtWO42ztB1EZqSsfIgf97Ic',
    appId: '1:521661363433:ios:8393b3bd8ac5ce17466c78',
    messagingSenderId: '521661363433',
    projectId: 'projeektekmo',
    storageBucket: 'projeektekmo.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}